[tool.ruff]
select = ["B", "E", "F", "FIX", "I", "T20"]
line-length = 200
ignore = ["T201"]  # ignore print statements

[build-system]
requires = [
    "numpy",
    "setuptools",
    "wheel",
    "Cython"
]
build-backend = "setuptools.build_meta"
